/*
* This file is auto-generated by the EnumCrafter codegen tool.
*
* Do not edit this file manually.
* It is regenerated automatically as the project evolves,
* based on the latest enum declarations and metadata.
*
* Any changes made here will be overwritten.
* To modify enum reflection behavior, update the source enums or the codegen inputs.
*/

#pragma once

#include "src/DisplayConfig.hpp"
#include "src/FusionBusItem.hpp"
#include "src/LogDispatcherStatus.hpp"
#include "src/SignalNameResolver.hpp"
#include "src/SignalRouterItem.hpp"
#include "src/StatusCode.hpp"
#include "src/VentDriveItem.hpp"
#include "src/WebApiService.hpp"

#include <array>
#include <string_view>
#include <optional>

namespace EnumCrafter {
template<typename EnumType>
constexpr std::optional<EnumType> parse(std::string_view);

template<typename EnumType>
constexpr std::array<EnumType, 0> makeIterable = {};


constexpr std::string_view toString(SignalNameResolver::SignalType e) {
    switch (e) {
        case SignalNameResolver::SignalType::Broadcaster: return "Broadcaster";
        case SignalNameResolver::SignalType::Listener: return "Listener";
        default: return "???";
    }
}

constexpr std::string_view toString(FusionBusItem::DeviceType e) {
    switch (e) {
        case FusionBusItem::DeviceType::VentDrive: return "VentDrive";
        case FusionBusItem::DeviceType::TempSensor: return "TempSensor";
        case FusionBusItem::DeviceType::SoilSensor: return "SoilSensor";
        case FusionBusItem::DeviceType::Unknown: return "Unknown";
        default: return "???";
    }
}

constexpr std::string_view toString(WebApiService::Method e) {
    switch (e) {
        case WebApiService::Method::Get: return "Get";
        case WebApiService::Method::Post: return "Post";
        case WebApiService::Method::Put: return "Put";
        case WebApiService::Method::Delete: return "Delete";
        default: return "???";
    }
}

constexpr std::string_view toString(SignalRouterItem::Mode e) {
    switch (e) {
        case SignalRouterItem::Mode::SingleSource: return "SingleSource";
        case SignalRouterItem::Mode::AndWithAuxiliary: return "AndWithAuxiliary";
        case SignalRouterItem::Mode::OrWithAuxiliary: return "OrWithAuxiliary";
        default: return "???";
    }
}

constexpr std::string_view toString(StatusCode e) {
    switch (e) {
        case StatusCode::SUCCESS: return "SUCCESS";
        case StatusCode::NOT_FOUND: return "NOT_FOUND";
        case StatusCode::ERROR: return "ERROR";
        default: return "???";
    }
}

constexpr std::string_view toString(LogDispatcherStatus e) {
    switch (e) {
        case LogDispatcherStatus::Idle: return "Idle";
        case LogDispatcherStatus::Running: return "Running";
        case LogDispatcherStatus::StorageFullError: return "StorageFullError";
        case LogDispatcherStatus::StorageNotReadyError: return "StorageNotReadyError";
        default: return "???";
    }
}

constexpr std::string_view toString(VentDriveItem::State e) {
    switch (e) {
        case VentDriveItem::State::Unknown: return "Unknown";
        case VentDriveItem::State::Closing: return "Closing";
        case VentDriveItem::State::Opening: return "Opening";
        case VentDriveItem::State::Idle: return "Idle";
        case VentDriveItem::State::Error: return "Error";
        case VentDriveItem::State::Uninitialized: return "Uninitialized";
        default: return "???";
    }
}

constexpr std::string_view toString(DisplayConfig::DisplayType e) {
    switch (e) {
        case DisplayConfig::DisplayType::None: return "None";
        case DisplayConfig::DisplayType::Oled: return "Oled";
        case DisplayConfig::DisplayType::CharLcd: return "CharLcd";
        default: return "???";
    }
}

template<>
constexpr std::optional<SignalNameResolver::SignalType> parse<SignalNameResolver::SignalType>(std::string_view s) {
    if (s == "Broadcaster") return SignalNameResolver::SignalType::Broadcaster;
    if (s == "Listener") return SignalNameResolver::SignalType::Listener;
    return std::nullopt;
}

template<>
constexpr std::optional<FusionBusItem::DeviceType> parse<FusionBusItem::DeviceType>(std::string_view s) {
    if (s == "VentDrive") return FusionBusItem::DeviceType::VentDrive;
    if (s == "TempSensor") return FusionBusItem::DeviceType::TempSensor;
    if (s == "SoilSensor") return FusionBusItem::DeviceType::SoilSensor;
    if (s == "Unknown") return FusionBusItem::DeviceType::Unknown;
    return std::nullopt;
}

template<>
constexpr std::optional<WebApiService::Method> parse<WebApiService::Method>(std::string_view s) {
    if (s == "Get") return WebApiService::Method::Get;
    if (s == "Post") return WebApiService::Method::Post;
    if (s == "Put") return WebApiService::Method::Put;
    if (s == "Delete") return WebApiService::Method::Delete;
    return std::nullopt;
}

template<>
constexpr std::optional<SignalRouterItem::Mode> parse<SignalRouterItem::Mode>(std::string_view s) {
    if (s == "SingleSource") return SignalRouterItem::Mode::SingleSource;
    if (s == "AndWithAuxiliary") return SignalRouterItem::Mode::AndWithAuxiliary;
    if (s == "OrWithAuxiliary") return SignalRouterItem::Mode::OrWithAuxiliary;
    return std::nullopt;
}

template<>
constexpr std::optional<StatusCode> parse<StatusCode>(std::string_view s) {
    if (s == "SUCCESS") return StatusCode::SUCCESS;
    if (s == "NOT_FOUND") return StatusCode::NOT_FOUND;
    if (s == "ERROR") return StatusCode::ERROR;
    return std::nullopt;
}

template<>
constexpr std::optional<LogDispatcherStatus> parse<LogDispatcherStatus>(std::string_view s) {
    if (s == "Idle") return LogDispatcherStatus::Idle;
    if (s == "Running") return LogDispatcherStatus::Running;
    if (s == "StorageFullError") return LogDispatcherStatus::StorageFullError;
    if (s == "StorageNotReadyError") return LogDispatcherStatus::StorageNotReadyError;
    return std::nullopt;
}

template<>
constexpr std::optional<VentDriveItem::State> parse<VentDriveItem::State>(std::string_view s) {
    if (s == "Unknown") return VentDriveItem::State::Unknown;
    if (s == "Closing") return VentDriveItem::State::Closing;
    if (s == "Opening") return VentDriveItem::State::Opening;
    if (s == "Idle") return VentDriveItem::State::Idle;
    if (s == "Error") return VentDriveItem::State::Error;
    if (s == "Uninitialized") return VentDriveItem::State::Uninitialized;
    return std::nullopt;
}

template<>
constexpr std::optional<DisplayConfig::DisplayType> parse<DisplayConfig::DisplayType>(std::string_view s) {
    if (s == "None") return DisplayConfig::DisplayType::None;
    if (s == "Oled") return DisplayConfig::DisplayType::Oled;
    if (s == "CharLcd") return DisplayConfig::DisplayType::CharLcd;
    return std::nullopt;
}

template<>
constexpr std::array<SignalNameResolver::SignalType, 2> makeIterable<SignalNameResolver::SignalType> = { SignalNameResolver::SignalType::Broadcaster, SignalNameResolver::SignalType::Listener };

template<>
constexpr std::array<FusionBusItem::DeviceType, 4> makeIterable<FusionBusItem::DeviceType> = { FusionBusItem::DeviceType::VentDrive, FusionBusItem::DeviceType::TempSensor, FusionBusItem::DeviceType::SoilSensor, FusionBusItem::DeviceType::Unknown };

template<>
constexpr std::array<WebApiService::Method, 4> makeIterable<WebApiService::Method> = { WebApiService::Method::Get, WebApiService::Method::Post, WebApiService::Method::Put, WebApiService::Method::Delete };

template<>
constexpr std::array<SignalRouterItem::Mode, 3> makeIterable<SignalRouterItem::Mode> = { SignalRouterItem::Mode::SingleSource, SignalRouterItem::Mode::AndWithAuxiliary, SignalRouterItem::Mode::OrWithAuxiliary };

template<>
constexpr std::array<StatusCode, 3> makeIterable<StatusCode> = { StatusCode::SUCCESS, StatusCode::NOT_FOUND, StatusCode::ERROR };

template<>
constexpr std::array<LogDispatcherStatus, 4> makeIterable<LogDispatcherStatus> = { LogDispatcherStatus::Idle, LogDispatcherStatus::Running, LogDispatcherStatus::StorageFullError, LogDispatcherStatus::StorageNotReadyError };

template<>
constexpr std::array<VentDriveItem::State, 6> makeIterable<VentDriveItem::State> = { VentDriveItem::State::Unknown, VentDriveItem::State::Closing, VentDriveItem::State::Opening, VentDriveItem::State::Idle, VentDriveItem::State::Error, VentDriveItem::State::Uninitialized };

template<>
constexpr std::array<DisplayConfig::DisplayType, 3> makeIterable<DisplayConfig::DisplayType> = { DisplayConfig::DisplayType::None, DisplayConfig::DisplayType::Oled, DisplayConfig::DisplayType::CharLcd };

} // namespace EnumCrafter
