import json
import os


def sanitize_include_path(path):
    rel_path = os.path.relpath(path, start=os.getcwd())
    return rel_path.replace("\\", "/")


def cpp_identifier(qualified_name):
    return qualified_name.replace("::", "_")


def emit_toString(enum):
    qname = enum["qualified_name"]
    lines = [f"constexpr std::string_view toString({qname} e) {{", "    switch (e) {"]
    for e in enum["enumerators"]:
        lines.append(f'        case {qname}::{e["name"]}: return "{e["name"]}";')
    lines.append('        default: return "???";')
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines)


def emit_parse(enum):
    qname = enum["qualified_name"]
    lines = [
        f"template<>",
        f"constexpr std::optional<{qname}> parse<{qname}>(std::string_view s) {{",
    ]
    for e in enum["enumerators"]:
        lines.append(f'    if (s == "{e["name"]}") return {qname}::{e["name"]};')
    lines.append("    return std::nullopt;")
    lines.append("}")
    return "\n".join(lines)


def emit_makeIterable(enum):
    qname = enum["qualified_name"]
    values = ", ".join(f'{qname}::{e["name"]}' for e in enum["enumerators"])
    count = len(enum["enumerators"])
    return f"template<>\nconstexpr std::array<{qname}, {count}> makeIterable<{qname}> = {{ {values} }};"


def generate_header(enums):
    includes = sorted(set(sanitize_include_path(e["file"]) for e in enums))
    include_block = "\n".join(f'#include "{path}"' for path in includes)
    autogen_comment = """/*
* This file is auto-generated by the EnumCrafter codegen tool.
*
* Do not edit this file manually.
* It is regenerated automatically as the project evolves,
* based on the latest enum declarations and metadata.
*
* Any changes made here will be overwritten.
* To modify enum reflection behavior, update the source enums or the codegen inputs.
*/
"""
    header = f"""{autogen_comment}
#pragma once

{include_block}

#include <array>
#include <string_view>
#include <optional>

namespace EnumCrafter {{
template<typename EnumType>
constexpr std::optional<EnumType> parse(std::string_view);

template<typename EnumType>
constexpr std::array<EnumType, 0> makeIterable = {{}};

"""

    for enum in enums:
        if not enum["is_scoped"]:
            continue
        header += "\n" + emit_toString(enum) + "\n"
    for enum in enums:
        if not enum["is_scoped"]:
            continue
        header += "\n" + emit_parse(enum) + "\n"
    for enum in enums:
        if not enum["is_scoped"]:
            continue
        header += "\n" + emit_makeIterable(enum) + "\n"

    header += "\n} // namespace EnumCrafter\n"
    return header


# Load JSON and generate header
with open("enum_metadata.json") as f:
    enums = json.load(f)

header_code = generate_header(enums)

with open("enumcrafter.hpp", "w") as out:
    out.write(header_code)
