/*
* This file is auto-generated by the EnumCrafter codegen tool.
*
* Do not edit this file manually.
* It is regenerated automatically as the project evolves,
* based on the latest enum declarations and metadata.
*
* Any changes made here will be overwritten.
* To modify enum reflection behavior, update the source enums or the codegen inputs.
*/

#pragma once

#include "src/SignalItem.hpp"
#include "src/SignalNameResolver.hpp"
#include "src/StatusCode.hpp"

#include <array>
#include <string_view>
#include <optional>

namespace EnumCrafter {
template<typename EnumType>
constexpr std::optional<EnumType> parse(std::string_view);

template<typename EnumType>
constexpr std::array<EnumType, 0> makeIterable = {};


constexpr std::string_view toString(SignalNameResolver::SignalType e) {
    switch (e) {
        case SignalNameResolver::SignalType::Broadcaster: return "Broadcaster";
        case SignalNameResolver::SignalType::Listener: return "Listener";
        default: return "???";
    }
}

constexpr std::string_view toString(SignalItem::Mode e) {
    switch (e) {
        case SignalItem::Mode::SingleSource: return "SingleSource";
        case SignalItem::Mode::AndWithAuxiliary: return "AndWithAuxiliary";
        case SignalItem::Mode::OrWithAuxiliary: return "OrWithAuxiliary";
        default: return "???";
    }
}

constexpr std::string_view toString(StatusCode e) {
    switch (e) {
        case StatusCode::SUCCESS: return "SUCCESS";
        case StatusCode::NOT_FOUND: return "NOT_FOUND";
        case StatusCode::ERROR: return "ERROR";
        default: return "???";
    }
}

template<>
constexpr std::optional<SignalNameResolver::SignalType> parse<SignalNameResolver::SignalType>(std::string_view s) {
    if (s == "Broadcaster") return SignalNameResolver::SignalType::Broadcaster;
    if (s == "Listener") return SignalNameResolver::SignalType::Listener;
    return std::nullopt;
}

template<>
constexpr std::optional<SignalItem::Mode> parse<SignalItem::Mode>(std::string_view s) {
    if (s == "SingleSource") return SignalItem::Mode::SingleSource;
    if (s == "AndWithAuxiliary") return SignalItem::Mode::AndWithAuxiliary;
    if (s == "OrWithAuxiliary") return SignalItem::Mode::OrWithAuxiliary;
    return std::nullopt;
}

template<>
constexpr std::optional<StatusCode> parse<StatusCode>(std::string_view s) {
    if (s == "SUCCESS") return StatusCode::SUCCESS;
    if (s == "NOT_FOUND") return StatusCode::NOT_FOUND;
    if (s == "ERROR") return StatusCode::ERROR;
    return std::nullopt;
}

template<>
constexpr std::array<SignalNameResolver::SignalType, 2> makeIterable<SignalNameResolver::SignalType> = { SignalNameResolver::SignalType::Broadcaster, SignalNameResolver::SignalType::Listener };

template<>
constexpr std::array<SignalItem::Mode, 3> makeIterable<SignalItem::Mode> = { SignalItem::Mode::SingleSource, SignalItem::Mode::AndWithAuxiliary, SignalItem::Mode::OrWithAuxiliary };

template<>
constexpr std::array<StatusCode, 3> makeIterable<StatusCode> = { StatusCode::SUCCESS, StatusCode::NOT_FOUND, StatusCode::ERROR };

} // namespace EnumCrafter
