; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@^6.12.0
board = esp32dev
framework = arduino
board_build.partitions = partitions/2MB-App_2MB-SPIFFS.csv
extra_scripts = WebBuildScript.py
build_unflags = 
	-std=gnu++11
	-std=gnu++14
build_flags = 
	-std=gnu++17
lib_deps = 
	fbiego/ESP32Time@2.0.4
	paulstoffregen/OneWire@2.3.8
	milesburton/DallasTemperature@3.11.0
	arduino-libraries/NTPClient@3.2.1
	esphome/ESPAsyncWebServer-esphome@3.2.2
	bblanchon/ArduinoJson@7.1.0
	olikraus/U8g2@2.35.19
	mobizt/Firebase ESP32 Client@4.3.19
	marcoschwartz/LiquidCrystal_I2C@1.1.4
	adafruit/RTClib@2.1.4
	marian-craciunescu/ESP32Ping@1.7
platform_packages = platformio/tool-esptoolpy@2.40900.0
